---
- name: Prune Docker Resources
  hosts: compose
  become: false
  tasks:
    - name: Cleanup old Docker Images and Containers
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true
      ignore_errors: true
