---
- name: Perform Filesystem Trim
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Run fstrim
      ansible.builtin.command: fstrim -av
      register: fstrim_result
      changed_when: "'trimmed' in fstrim_result.stdout"
