---
- name: Perform mailcow Update
  hosts: mailcow
  become: true
  vars:
    mailcow_path: /opt/mailcow-dockerized
  tasks:
    - name: Run mailcow update script
      ansible.builtin.command: ./update.sh --gc --force
      args:
        chdir: "{{ mailcow_path }}"
      register: mailcow_update_result
      changed_when: "'error' not in mailcow_update_result.stderr | lower"
