---
- name: Deploy Docker Pre-Requisites
  hosts: compose
  become: true
  vars:
    docker_packages:
      - docker-ce
      - docker-compose-plugin
      - python3-requests
  tasks:
    - name: Ensure docker packages are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ docker_packages }}"

    - name: Create Folder /docker if it does not exist
      ansible.builtin.file:
        state: directory
        path: /docker
        mode: "0755"
